"""
Consolidates scan results from Bandit, Safety, and Trivy
into a single Markdown summary report.
"""

import json
import os
from dataclasses import dataclass, field
from typing import List
from datetime import datetime, timezone


@dataclass
class Finding:
    tool: str
    severity: str
    title: str
    location: str
    cve: str = ""


@dataclass
class Report:
    generated_at: str
    findings: List[Finding] = field(default_factory=list)

    def by_severity(self, severity: str) -> List[Finding]:
        return [f for f in self.findings if f.severity.upper() == severity.upper()]


def parse_bandit(path: str) -> List[Finding]:
    findings = []
    if not os.path.exists(path):
        return findings
    with open(path) as f:
        data = json.load(f)
    for result in data.get("results", []):
        findings.append(Finding(
            tool="Bandit (SAST)",
            severity=result.get("issue_severity", "UNKNOWN"),
            title=result.get("issue_text", ""),
            location=f"{result.get('filename', '')}:{result.get('line_number', '')}"
        ))
    return findings


def parse_safety(path: str) -> List[Finding]:
    findings = []
    if not os.path.exists(path):
        return findings
    with open(path) as f:
        data = json.load(f)
    for vuln in data.get("vulnerabilities", []):
        findings.append(Finding(
            tool="Safety (SCA)",
            severity=vuln.get("severity", "UNKNOWN").upper(),
            title=vuln.get("advisory", ""),
            location=f"{vuln.get('package_name', '')} {vuln.get('analyzed_version', '')}",
            cve=vuln.get("CVE", "")
        ))
    return findings


def generate_markdown(report: Report) -> str:
    critical = report.by_severity("CRITICAL")
    high     = report.by_severity("HIGH")
    medium   = report.by_severity("MEDIUM")

    status_icon = "✅" if not critical and not high else "❌"

    lines = [
        "## 🔒 DevSecOps Security Report",
        f"**Generated:** {report.generated_at}",
        "",
        f"| Severity | Count |",
        f"|----------|-------|",
        f"| 🔴 Critical | {len(critical)} |",
        f"| 🟠 High | {len(high)} |",
        f"| 🟡 Medium | {len(medium)} |",
        "",
        f"**Pipeline Status: {status_icon}**",
        "",
    ]

    if critical:
        lines.append("### 🔴 Critical Findings")
        for f in critical:
            lines.append(f"- **[{f.tool}]** `{f.location}` — {f.title}"
                         + (f" ({f.cve})" if f.cve else ""))
        lines.append("")

    if high:
        lines.append("### 🟠 High Findings")
        for f in high:
            lines.append(f"- **[{f.tool}]** `{f.location}` — {f.title}"
                         + (f" ({f.cve})" if f.cve else ""))
        lines.append("")

    lines.append("---")
    lines.append("*Generated by DevSecOps Pipeline — ravishekharg/devsecops-pipeline*")
    return "\n".join(lines)


if __name__ == "__main__":
    report = Report(generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))

    report.findings.extend(parse_bandit("bandit-report/bandit-report.json"))
    report.findings.extend(parse_safety("safety-report/safety-report.json"))

    print(f"Total findings: {len(report.findings)}")
    print(f"  Critical : {len(report.by_severity('CRITICAL'))}")
    print(f"  High     : {len(report.by_severity('HIGH'))}")
    print(f"  Medium   : {len(report.by_severity('MEDIUM'))}")

    md = generate_markdown(report)
    with open("security-summary.md", "w") as f:
        f.write(md)
    print("\nReport saved to security-summary.md")